- name: Install and Configure WordPress
  hosts: server2
  become: true
  vars_files:
    - vars.yml
  tasks:
    - name: Install Nginx, PHP, and extensions
      apt:
        name:
          - nginx
          - php-fpm
          - php-mysql
          - php-curl
          - php-gd
          - php-mbstring
          - php-xml
        state: present
        update_cache: true
    
    - name: Get PHP-FPM version
      shell: php -v | head -n1 | cut -d' ' -f2 | cut -d'.' -f1,2
      register: php_version
      changed_when: false
    
    - name: Set PHP-FPM socket path
      set_fact:
        php_fpm_socket: "/run/php/php{{ php_version.stdout }}-fpm.sock"
    
    - name: Nginx Status
      service:
        name: nginx
        state: started
        enabled: true
    
    - name: Start PHP-FPM
      service:
        name: "php{{ php_version.stdout }}-fpm"
        state: started
        enabled: true
    
    - name: Install Python3 MySQL support
      apt:
        name: python3-pymysql
        state: present
    
    - name: Install MariaDB
      apt:
        name: mariadb-server
        state: present
    
    - name: MariaDB Status
      service:
        name: mariadb
        state: started
        enabled: true
    
    - name: WordPress DB
      mysql_db:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: "{{ wp_db_name }}"
        state: present
    
    - name: WordPress DB User
      mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: "{{ wp_db_user }}"
        password: "{{ wp_db_password }}"
        priv: "{{ wp_db_name }}.*:ALL"
        host: "localhost"
        state: present
    
    - name: Download WordPress
      get_url:
        url: "https://wordpress.org/latest.tar.gz"
        dest: /tmp/wordpress.tar.gz
    
    - name: Extract WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /tmp/
        remote_src: yes
    
    - name: Create WordPress directory
      file:
        path: /var/www/{{ wp_site_dir }}
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'
    
    - name: Copy WordPress To Web Root
      synchronize:
        src: /tmp/wordpress/
        dest: /var/www/{{ wp_site_dir }}/
      delegate_to: "{{ inventory_hostname }}"
    
    - name: Set WordPress permissions
      file:
        path: /var/www/{{ wp_site_dir }}
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes
    
    - name: Create wp-config.php
      template:
        src: wp-config.php.j2
        dest: "/var/www/{{ wp_site_dir }}/wp-config.php"
        owner: www-data
        group: www-data
        mode: '0644'
    
    - name: Deploy Nginx WordPress Conf
      template:
        src: nginx-wordpress.conf.j2
        dest: /etc/nginx/sites-available/wordpress
      notify: Reload Nginx
    
    - name: Enable WordPress
      file:
        src: /etc/nginx/sites-available/wordpress
        dest: /etc/nginx/sites-enabled/wordpress
        state: link
      notify: Reload Nginx
    
    - name: Remove Default Nginx 
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: Reload Nginx
  
  handlers:          
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded